CashControl/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CashControl.Models;
using Microsoft.AspNetCore.Authorization;

namespace CashControl.Controllers
{
    [Authorize]
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
              return View(await _context.Categories.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryID == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return View(new Category());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryID,Name,Emoji,Type")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryID,Name,Emoji,Type")] Category category)
        {
            if (id != category.CategoryID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CategoryID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryID == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Categories'  is null.");
            }
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
          return _context.Categories.Any(e => e.CategoryID == id);
        }
    }
}

CashControl/Controllers/DashboardController.cs
using CashControl.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.SqlServer.Server;
using Syncfusion.EJ2.Inputs;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Security.Claims;

namespace CashControl.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly ApplicationDbContext _context;
        public DashboardController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<ActionResult> Index()
        {

            // Get the currently logged-in user's ID
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);



            //Tranzactiile pe ultimele 7 zile
            DateTime DataInceput = DateTime.Today.AddDays(-6);
            DateTime DataFinal = DateTime.Today;

            List<Transaction> SelectedTransactions = await _context.Transactions
                .Include(x => x.Category)
                .Where(y => y.Date >= DataInceput && y.Date <= DataFinal && y.ApplicationUserId == userId)
                .ToListAsync();
            //List<Transaction> SelectedTransactions = await _context.Transactions
            //    .Include(x => x.Category)
            //    .Where(y => y.Date >= DataInceput && y.Date <= DataFinal)
            //    .ToListAsync();

            //Total venituri

            int VenitTotal = SelectedTransactions
                .Where(i => i.Category.Type == "Venit")
                .Sum(j => j.Total);
            ViewBag.VenitTotal = VenitTotal.ToString("C0");

            //Total cheltuieli

            int CheltuieliTotale = SelectedTransactions
                .Where(i => i.Category.Type == "Cheltuiala")
                .Sum(j => j.Total);
            ViewBag.CheltuieliTotale = CheltuieliTotale.ToString("C0");

            //Balanta 

            int Balanta = VenitTotal - CheltuieliTotale;
            CultureInfo culture = CultureInfo.CreateSpecificCulture("ro-RO");
            culture.NumberFormat.CurrencyNegativePattern = 1;
            ViewBag.Balanta = String.Format(culture, "{0:C0}", Balanta);

            //Numarul total de tranzactii

            int NumarTranzactii = SelectedTransactions.Count();
            ViewBag.NumarTranzactii = NumarTranzactii;

            //Donut chart -> Cheltuieli in fct de categorie

            ViewBag.DonutChartData = SelectedTransactions
                .Where(i => i.Category.Type == "Cheltuiala")
                .GroupBy(j => j.Category.CategoryID)
                .Select(k => new
                {
                    CategorieCuEmoji = k.First().Category.Emoji + " " + k.First().Category.Name,
                    total = k.Sum(j => j.Total),
                    formatedTotal = k.Sum(j => j.Total).ToString("C0"),
                })
                .OrderByDescending(l => l.total)
                .ToList();

            //Spline chart -> Cheltuieli & Venituri

            //Venit
            List<SplineChartData> RezumatVenituri = SelectedTransactions
                .Where(i => i.Category.Type == "Venit")
                .GroupBy(j => j.Date)
                .Select(k => new SplineChartData()
                {
                    zi = k.First().Date.ToString("dd-MMM", new CultureInfo("ro-RO")),
                    venit = k.Sum(l => l.Total)
                }).ToList();

            //Cheltuiala
            List<SplineChartData> RezumatCheltuieli = SelectedTransactions
                .Where(i => i.Category.Type == "Cheltuiala")
                .GroupBy(j => j.Date)
                .Select(k => new SplineChartData()
                {
                    zi = k.First().Date.ToString("dd-MMM", new CultureInfo("ro-RO")),
                    cheltuiala = k.Sum(l => l.Total)
                }).ToList();

            //Venituri si cheltuieli combinate

            string[] Ultimele7Zile = Enumerable.Range(0, 7)
                .Select(i => DataInceput.AddDays(i).ToString("dd-MMM", new CultureInfo("ro-RO")))
                .ToArray();

            ViewBag.SplineChartData = from zi in Ultimele7Zile
                                      join venit in RezumatVenituri on zi equals venit.zi
                                      into VenitZilnic
                                      from venit in VenitZilnic.DefaultIfEmpty()
                                      join cheltuiala in RezumatCheltuieli on zi equals cheltuiala.zi into CheltuialaZilnica
                                      from cheltuiala in CheltuialaZilnica.DefaultIfEmpty()
                                      select new
                                      {
                                          zi = zi,
                                          venit = venit == null ? 0 : venit.venit,
                                          cheltuiala = cheltuiala == null ? 0 : cheltuiala.cheltuiala,
                                      };

            // Tranzactii recente (ultimele tranzactii)

            //ViewBag.TranzactiiRecente = await _context.Transactions
            //  .Include(i => i.Category)
            //  .OrderByDescending(j => j.Date)
            //  .Take(9)
            //  .ToListAsync();

            var recentTransactions = await _context.Transactions
                .Include(i => i.Category)
                .Where(t => t.ApplicationUserId == userId) // Filter by user ID
                .OrderByDescending(j => j.Date)
                .Take(9)
                .ToListAsync();
            ViewBag.TranzactiiRecente = recentTransactions;

            // Bar chart -> Rezumat balanta

            List<BarChartData> RezumatBalanta = SelectedTransactions
                .GroupBy(j => j.Date)
                .Select(k => new BarChartData()
                {
                    zi = k.First().Date.ToString("dd-MMM", new CultureInfo("ro-RO")),
                    balanta = k.Sum(l => l.Category.Type == "Venit" ? l.Total : -l.Total)
                })
                .OrderBy(m => m.zi)
                .ToList();

            ViewBag.BarChartData = from zi in Ultimele7Zile
                                   join balanta in RezumatBalanta on zi equals balanta.zi
                                   into BalantaZilnica
                                   from balanta in BalantaZilnica.DefaultIfEmpty()
                                   select new
                                   {
                                       zi = zi,
                                       balanta = balanta == null ? 0 : balanta.balanta,
                                   };

            return View();
        }
    }

    public class SplineChartData
    {
        public string zi;
        public int venit;
        public int cheltuiala;
    }

    public class BarChartData
    {
        public string zi;
        public int balanta;
    }
}







//using CashControl.Models;
//using Microsoft.AspNetCore.Authorization;
//using Microsoft.AspNetCore.Mvc;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.SqlServer.Server;
//using Syncfusion.EJ2.Inputs;
//using System.ComponentModel.DataAnnotations;
//using System.Globalization;


//namespace CashControl.Controllers
//{
//    [Authorize]
//    public class DashboardController : Controller
//    {
//        private readonly ApplicationDbContext _context;
//        public DashboardController(ApplicationDbContext context) { 
//                _context= context;
//        }

//        public async Task<ActionResult> Index()
//        {

//            //Tranzactiile pe ultimele 7 zile
//            DateTime DataInceput = DateTime.Today.AddDays(-6);
//                DateTime DataFinal = DateTime.Today;

//            List<Transaction> SelectedTransactions = await _context.Transactions
//                .Include(x => x.Category)
//                .Where(y => y.Date >= DataInceput && y.Date <= DataFinal)
//                .ToListAsync();

//            //Total venituri

//            int VenitTotal = SelectedTransactions
//                .Where(i => i.Category.Type == "Venit")
//                .Sum(j => j.Total);
//            ViewBag.VenitTotal = VenitTotal.ToString("C0");

//            //Total cheltuieli

//            int CheltuieliTotale = SelectedTransactions
//                .Where(i => i.Category.Type == "Cheltuiala")
//                .Sum(j => j.Total);
//            ViewBag.CheltuieliTotale = CheltuieliTotale.ToString("C0");

//            //Balanta 

//            int Balanta = VenitTotal - CheltuieliTotale;
//            CultureInfo culture = CultureInfo.CreateSpecificCulture("ro-RO");
//            culture.NumberFormat.CurrencyNegativePattern = 1;
//            ViewBag.Balanta = String.Format(culture, "{0:C0}", Balanta);

//            //Numarul total de tranzactii

//            int NumarTranzactii = SelectedTransactions.Count();
//            ViewBag.NumarTranzactii = NumarTranzactii;

//            //Donut chart -> Cheltuieli in fct de categorie

//            ViewBag.DonutChartData = SelectedTransactions
//                .Where(i => i.Category.Type == "Cheltuiala")
//                .GroupBy(j => j.Category.CategoryID)
//                .Select(k => new
//                {
//                    CategorieCuEmoji = k.First().Category.Emoji+" "+ k.First().Category.Name,
//                    total = k.Sum(j => j.Total),
//                    formatedTotal = k.Sum(j => j.Total).ToString("C0"),
//                })
//                .OrderByDescending(l => l.total)
//                .ToList();

//            //Spline chart -> Cheltuieli & Venituri

//            //Venit
//            List<SplineChartData> RezumatVenituri = SelectedTransactions
//                .Where(i => i.Category.Type == "Venit")
//                .GroupBy(j => j.Date)
//                .Select(k => new SplineChartData()
//                {

CashControl/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CashControl</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @*<link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/20.4.48/material.css" />*@
    <link href="https://cdn.syncfusion.com/ej2/20.4.48/bootstrap5.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css"> @*pentru a importa icons*@
    @*<link href="https://fonts.googleapis.com/css2?family=Golos+Text:wght@400;600;800&family=Oswald:wght@500&display=swap" rel="stylesheet">*@
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CashControl.styles.css" asp-append-version="true" />
    <script src="https://cdn.syncfusion.com/ej2/20.4.48/dist/ej2.min.js"></script>
</head>
<body class="e-bigger">
    <header> 
        @*Nav bar*@
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> <img class="navbar-logo" src="~/poze/money_icon.png" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-center">
                    <ul class="navbar-nav d-flex justify-content-center flex-grow-1">  @* Am adaugat d-flex si justify content pentru a centra elementele din navbar*@
                        <li class="nav-item">
                            <a class="nav-link text-dark bi bi-house-door" asp-area="" asp-controller="Home" asp-action="Index">Acasa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark bi bi-list" asp-area="" asp-controller="Categories" asp-action="Index">Categorii</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark bi bi-cash-coin" asp-area="" asp-controller="Transactions" asp-action="Index">Tranzactii</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark bi bi-speedometer2" asp-area="" asp-controller="Dashboard" asp-action="Index">Tablou</a>
                        </li>
                       @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@                  
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="com-md-10">
                <main role="main" class="pb-3">
                    <div class="row">
                        <div class="col-md-7">
                            <div class="d-flex flex-column mb-5">
                                <div class="d-flex mb-1 child">
                                    @*clasa child pt centrare*@
                                    <div class="flex-grow-1">
                                        <h3 class="fw-bold">@ViewData["TitluPagina"]</h3>
                                    </div>
                                    <div style="position:relative; left:550px; top:2px;">
                                        @if (ViewData["CreareText"] != null)
                                        {
                                            <a class="btn btn-success" style="color: white" href="@ViewData["CreareURL"]">
                                                @ViewData["CreareText"]
                                            </a>
                                        }
                                    </div>
                                </div>
                                @* portiunea pentru breadcrumb*@
                                @*  <ejs-breadcrumb id="breadcrumb"></ejs-breadcrumb>*@
                            </div>
                        </div>
                    </div>
                    @RenderBody()
                </main>
            </div>
        </div>

    </div>

    @* Buton up to top*@
    <div class="up-to-top">
        <button id="scroll-to-top-button" onclick="scrollToTop()"><i class="bi bi-arrow-up-short"></i></button>
    </div>
    
    @* Footer *@

    <footer class="border-top footer text-muted">
        <div class="container d-flex justify-content-between align-items-center">
            <div class="left">
                <p>&copy; 2023 - CashControl</p>
            </div>
            <div class="right">
                <nav>
                    <a href="#" class="social-icon"><i class="bi bi-facebook"></i></a>
                    <a href="#" class="social-icon"><i class="bi bi-instagram"></i></a>
                    <a href="#" class="social-icon"> <i class="bi bi-github"></i></a>
                    <a asp-area="" asp-controller="Home" asp-action="Contact">Contacteaza-ne</a>
                    <a asp-area="" asp-controller="Home" asp-action="Despre">Despre</a>
                    <a asp-area="" asp-controller="Home" asp-action="TermeniConditii">Termeni si conditii</a>
                </nav>
            </div>
        </div>
    </footer>

    <script>
        const scrollToTopButton = document.getElementById("scroll-to-top-button");
        window.addEventListener("scroll", () => {
            if (window.pageYOffset > 0) {
                scrollToTopButton.style.display = "block";
            } else {
                scrollToTopButton.style.display = "none";
            }
        });

        function scrollToTop() {
            window.scrollTo({ top: 0, behavior: "smooth" });
        }
    </script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/lib/qrcode.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <ejs-scripts></ejs-scripts>
    
</body>
</html>